sudo: required

environment:
  - RELEASE_VERSION=`cat release_version.txt`

services:
  - docker

before_install:
  - docker-compose -f docker-compose.build.yml build

before_script:
  - docker tag rezme/registry-server:latest rezme/registry-server:$RELEASE_VERSION

script:
  - docker login --username $DOCKER_LOGIN_USERNAME --password $DOCKER_LOGIN_PASSWORD
  - docker push rezme/registry-server:latest
  - docker push rezme/registry-server:$RELEASE_VERSION

after_script:
  - docker pull rezme/registry-server:latest
  - docker pull rezme/registry-server:$RELEASE_VERSION
