version: '2'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./storage/:/data/db

  redis:
    image: redis:3.0.7-alpine
    ports:
      - "6379:6379"

  registry-server:
    image: rezme/registry-server
    env_file: env-example
    links:
      - mongo
      - redis
    ports:
      - 5000:5000
      - 3000:3000