version: '2'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./storage/:/data/db

  redis:
    image: redis:3.0.7-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"

  registry-server:
    image: rezme/registry-server
    build: .
    env_file: env-example
    depends_on:
      - mongo
      - redis
    ports:
      - 5000:5000
      - 3000:3000
    volumes:
      - ./controller:/registry-server/controller
      - ./lib:/registry-server/lib
      - ./middleware:/registry-server/middleware
      - ./models:/registry-server/models
      - ./public:/registry-server/public
      - ./templates:/registry-server/templates
      - ./test:/registry-server/test
      - ./views:/registry-server/views
      - ./csrf.js:/registry-server/csrf.js
      - ./server.js:/registry-server/server.js
      - ./template-helper.js:/registry-server/template-helper.js
      - ./package.json:/registry-server/package.json
    command: /bin/sh -c "npm install -g nodemon ; nodemon server.js"
      