version: '2'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./storage/:/data/db

  redis:
    image: redis:3.0.7-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"

  registry-server:
    image: rezme/registry-server
    build: .
    env_file: env-example
    depends_on:
      - mongo
      - redis
    ports:
      - 5000:5000
    volumes:
      - .:/registry-server
    command: /bin/sh -c "npm install -g nodemon ; nodemon server.js"